//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementVersion2
{
    using System;
    using System.Collections.Generic;
    
    public partial class BienLai
    {
        public int MaBienLai { get; set; }
        public Nullable<int> MaDocGia { get; set; }
        public System.DateTime NgayTraTT { get; set; }
        public string HinhThucThanhToan { get; set; }
        public decimal TienTra { get; set; }
    
        public virtual DocGia DocGia { get; set; }
    }
}
