//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementVersion2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuonSach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuonSach()
        {
            this.PhieuMuonSaches = new HashSet<PhieuMuonSach>();
        }
    
        public int MaCuonSach { get; set; }
        public int MaDauSach { get; set; }
        public string TrangThaiSach { get; set; }
        public string TenCuonSach { get; set; }
    
        public virtual DauSach DauSach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuMuonSach> PhieuMuonSaches { get; set; }
    }
}
