//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementVersion2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DauSach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DauSach()
        {
            this.CuonSaches = new HashSet<CuonSach>();
            this.TacGias = new HashSet<TacGia>();
        }
    
        public int MaDauSach { get; set; }
        public int MaTheLoai { get; set; }
        public Nullable<int> MaNXB { get; set; }
        public string TenDauSach { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> NamXuatBan { get; set; }
        public Nullable<decimal> GiaTien { get; set; }
        public Nullable<int> SoTrang { get; set; }
        public string NgonNgu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuonSach> CuonSaches { get; set; }
        public virtual NXB NXB { get; set; }
        public virtual TheLoai TheLoai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TacGia> TacGias { get; set; }
    }
}
