//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementVersion2
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiPhieuMuon
    {
        public int MaLPhieuMuon { get; set; }
        public string TenMPM { get; set; }
        public Nullable<decimal> ChiPhi { get; set; }
    }
}
