//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementVersion2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MuonSach
    {
        public int MaMuonSach { get; set; }
        public Nullable<int> MaPhieu { get; set; }
        public System.DateTime NgayMuon { get; set; }
        public System.DateTime NgayTra { get; set; }
        public string TrangThaiM { get; set; }
        public Nullable<decimal> GiaMuon { get; set; }
        public Nullable<int> SoNgayMuon { get; set; }
        public Nullable<decimal> TienCoc { get; set; }
    
        public virtual PhieuMuonSach PhieuMuonSach { get; set; }
    }
}
